version: '2'
services:
   emane:
      build:
         context: .
         dockerfile: Dockerfile.emane
      image: emane:latest
   emane-tutorials:
      build:
         context: .
         dockerfile: Dockerfile.emane_tutorials
      image: emane-tutorials:latest
      depends_on:
         - emane
